### ISSUE TITLE
multi language translate to traditional chinese 

### ISSUE THREAD

**Issue by terryhcw** [Enough-Software/enough_mail_app#57]
Hi all, 
    I want to help add one more language to Maily. I had test and make some change of character in chinese, which it is work and can run in the android simulator. But after few hours of work, it can not compile again and run in the simulator.
    I get the following error message : 

    Generating synthetic localizations package failed with 1 error:

Exception: The following .arb file's locale could not be determined: 
D:\GitHub\enough_mail_app\enough_mail_app\lib/l10n\app_ct.arb 
Make sure that the locale is specified in the file's '@@locale' property or as part of the filename (e.g. file_en.arb)

    Does it mean I did not use the same standard code for chinese language? In my environment I use 'ct' for traditional chinese, 
I had add app.ct.arb file in the "lib/l10n" directory and also add app_localizations_ct.dart file in the "flutter_gen/gen_l10n" directory. Also I has add and change some code in "app_localizations.dart" to support this language.

     If I'm working on a work way, please add the relate language in the project, Then I will translate the language file to chinese. If possible, I can help to translate it simplifies chinese and Traditonal chinese or some degree extend to Hong Kong and Taiwan style for Traditional Chinese
   
     Regards
Terry Ho

**Comment by robert-virkus** [comment]
Hi Terry,

this is great news, I would love to support Chinese! 
In regards to your build error, I am unsure what the cause for this is. Maily uses the "standard" way of Flutter localization. As far as I know the generic language tag for Chinese is "zh", have you tried using `zh` instead of `ct`?
As Chinese has many  different scripts, here's also some documentation about the definition options:
https://flutter.dev/docs/development/accessibility-and-localization/internationalization#advanced-locale-definition

In any case, please consider creating a pull request even in a non-working state, we can then resolve this together.
